
import "./globals.css";
import {ReactQueryProvider} from './components/react-query-provider/ReactQueryProvider'

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReactQueryProvider>
      <html lang="en" suppressHydrationWarning>
        <body>
          <header className="bg-blue-600 text-white py-4 shadow-md">
            <div className="container mx-auto px-6">
              <h1 className="text-lg font-semibold">Plant Search</h1>
            </div>
          </header>
          <main className="flex-1 bg-gray-100">
            <div className="container mx-auto px-6 py-4">{children}</div>
          </main>
          <footer className="bg-blue-600 text-white py-4 mt-auto">
            <div className="container mx-auto px-6 text-center">
              <p>&copy; 2024 Plant Finder. All rights reserved.</p>
            </div>
          </footer>
        </body>

      </html>
    </ReactQueryProvider>
  );
}
